sources:
  - name: s1
    database: SBI_DB
    schema : SBI_SCHEMA
    tables:
      - name: t_nation
      - name: t_customer
      - name: CUSTOMER
      - name: orders
      - name: payment
      - name: t_ticket
      