sources:
  - name: s1
    database: SBI_DB
    schema : SBI_SCHEMA
    tables:
      - name: t_nation
      - name: t_customer
      - name: TB_CUSTOMER
      - name: DIM_CUSTOMER_HISTORY
      - name: CUSTOMER_DEV
      - name: t_ticket
      - name: RAW_TRANSACTIONS