      sources:
  - name: s1
    database: SBI_DB
    schema: SBI_SCHEMA

    tables:
      - name: t_nation
      - name: t_customers
      - name: customer
      - name: orders
      - name: products
      - name: emp
      - name: cust_info