      sources:
  - name: s1
    database: SBI_DB
    schema: DBT_SCHEMA

    tables:
      - name: t_nation
      - name: t_customer
      - name: customer
      - name: orders
      - name: products